#cloud-config
coreos:
  units:
    - name: nodeapp.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=nodeapp
        Require=docker.service
        After=docker.service
        [Service]
        ExecStartPre=-/usr/bin/docker rm -f nodeapp
        ExecStart=/bin/bash -c "docker run --rm --name nodeapp -p 80:8000 \
          -e COREOS_PUBLIC_IPV4=$public_ipv4 \
          -e INSTANCE_ID=%H \
          xueshanf/docker-nodeapp:latest"
        ExecStop=-/usr/bin/docker stop nodeapp
        RestartSec=5
        Restart=always

write_files:
  - path: /etc/profile.d/alias.sh
    content: |
        alias lal="ls -al"
        alias ll="ls -l"
        alias sd="sudo systemctl"
        alias sdl="sd list-units"
        alias sds="sd status"
        alias sdcat="sd cat"
        alias j="sudo journalctl"
        alias jfu="j -f -u"
        alias dk="docker "
        alias dkc="dk ps"
        alias dkm="dk images"
        alias dki="dk inspect"
        alias dkb="dk build"
        alias dke="dk exec"
        function dkip() { docker inspect --format "{{ .NetworkSettings.IPAddress }}" $1 ; }
        function dkid() { docker inspect --format "{{ .ID }}" $1 ; }
# end of files




