#cloud-config
coreos:
  units:
    - name: docker-openvpn.service
      content: |[Unit]
        Description=OpenVPN Docker Container
        Documentation=https://github.com/kylemanna/docker-openvpn
        After=network.target docker.socket
        Requires=docker.socket

        [Service]
        RestartSec=10
        Restart=always

        Environment="NAME=ovpn"
        Environment="DATA_VOL=/var/lib/apps/ovpn"
        Environment="IMG=kylemanna/openvpn:latest"
        Environment="PORT=1194:1194/udp"

        # To override environment variables, use local configuration directory:
        # /etc/systemd/system/docker-openvpn.d/local.conf
        # http://www.freedesktop.org/software/systemd/man/systemd.unit.html

        # Clean-up bad state if still hanging around
        ExecStartPre=-/usr/bin/docker rm -f $NAME

        # Attempt to pull new image for security updates
        ExecStartPre=-/usr/bin/docker pull $IMG

        # Main process
        ExecStart=/usr/bin/docker run --rm -v${DATA_VOL}:/etc/openvpn --name ${NAME} \
          --cap-add=NET_ADMIN -p ${PORT} ${IMG} ovpn_run

        [Install]
        WantedBy=multi-user.target

write_files:
  - path: /etc/profile.d/alias.sh
    content: |
        alias lal="ls -al"
        alias ll="ls -l"
        alias sd="sudo systemctl"
        alias sdl="sd list-units"
        alias sds="sd status"
        alias sdcat="sd cat"
        alias j="sudo journalctl"
        alias jfu="j -f -u"
        alias dk="docker "
        alias dkc="dk ps"
        alias dkm="dk images"
        alias dki="dk inspect"
        alias dkb="dk build"
        alias dke="dk exec"
        function dkip() { docker inspect --format "{{ .NetworkSettings.IPAddress }}" $1 ; }
        function dkid() { docker inspect --format "{{ .ID }}" $1 ; }
# end of files

